name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{secrets.DOCKER_USERNAME}}/pytorch-24.04-py3-mlperf
      # IMAGE_TAG: ${{}}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:pytorch"
        file: pytorch-24.04-py3-mlperf.dockerfile
        platforms: linux/x86_64,linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
